# .github/workflows/build.yml
name: Build NHBosses

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Build with Maven
        run: mvn -B -DskipTests package

      - name: Upload plugin jar
        uses: actions/upload-artifact@v4
        with:
          name: NHBosses
          path: target/NHBosses.jar

